name: Food Delivery CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4
      - name: Verifying code
        run:  ls -R
      - name: seeing changes
        run: echo "I have my code"